<?xml version="1.0" encoding="UTF-8"?>
	<!--
		Designed and generated by Altova StyleVision Enterprise Edition 2010
		rel. 3 - see http://www.altova.com/stylevision for more information.
	-->
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:clitype="clitype"
	xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
	xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java"
	xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi"
	xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:altova="http://www.altova.com"
	exclude-result-prefixes="clitype fn iso4217 ix java link xbrldi xbrli xlink xs xsi altova">
	<xsl:output version="4.0" method="html" indent="no"
		encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"
		doctype-system="http://www.w3.org/TR/html4/loose.dtd" />
	<xsl:param name="SV_OutputFormat" select="'HTML'" />
	<xsl:variable name="XML" select="/" />
	<xsl:variable name="packages" select="/Itinerary/packages" />
	<xsl:variable name="flights" select="/Itinerary/flights" />
	<xsl:variable name="hotels" select="/Itinerary/hotels" />
	<xsl:variable name="insurances" select="/Itinerary/insurances" />
	<xsl:variable name="services" select="/Itinerary/services" />
	<xsl:variable name="promoId" select="/Itinerary/bookingHeader/promoId" />
	<xsl:variable name="isRFAExists">
		<xsl:call-template name="checkRFAExists"/>
	</xsl:variable>
	<xsl:template match="/">
		<html>
			<head>
				<title>
					<xsl:text> </xsl:text>
				</title>
				<meta http-equiv="X-UA-Compatible" content="IE=7" />
				<xsl:comment>[if
					IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.60in; margin-right:0.60in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<table style="background-color:#ffffff; border-bottom:#a0a0a4 2px solid; border-left:#a0a0a4 2px solid; border-right:#a0a0a4 2px solid; border-top:#a0a0a4 2px solid; font-family:arial , helvetica , sans-serif; font-size:12px; " border="0" cellPadding="10" cellSpacing="0" width="675">
					<xsl:variable name="altova:CurrContextGrid_0BE6D380" select="."/>
					<tbody>
						<tr style="height:40px; ">
							<td style="width:405px; " vAlign="top">
								<img>
									<xsl:attribute name="src">
											<xsl:text>http://www.applevacations.com/appleweb/images/abe/avlogo.gif</xsl:text>
									</xsl:attribute>
									<xsl:attribute name="alt"/>
								</img>
							</td>
							<td style="color:#005e9d; font-size:24px; width:345px; " align="right" vAlign="top">
								<span>
									<xsl:text>Invoice</xsl:text>
								</span>
							</td>
						</tr>
						<tr>
							<td colspan="2" style="width:405px; ">
								<table border="0" style="font-size:12px" cellPadding="0" cellSpacing="0" width="675">
									<tbody>
										<tr style="height:69px; ">
											<td style="width:225px; ">
												<xsl:call-template name="agentName">
													<xsl:with-param name="agentFullName">
														<xsl:value-of select="/Itinerary/imApplicationInfo/selectedAgent/fullName" />
													</xsl:with-param>
													<xsl:with-param name="agentFirstName">
	      													<xsl:value-of select="/Itinerary/imApplicationInfo/selectedAgent/firstName" />
	    											</xsl:with-param>
	    											<xsl:with-param name="agentLastName">
	      													<xsl:value-of select="/Itinerary/imApplicationInfo/selectedAgent/lastName" />
	    											</xsl:with-param>
												</xsl:call-template>
												<br/>
												<xsl:value-of select="Itinerary/bookingHeader/agency/name"/>
												<br/>
												<xsl:value-of select="Itinerary/bookingHeader/agency/street"/>
												<br/>
												<xsl:value-of select="Itinerary/bookingHeader/agency/city"/>
												<br/>
												<xsl:value-of select="Itinerary/bookingHeader/agency/state"/>
												<span>
												<xsl:text>  </xsl:text>
												</span>
												<xsl:value-of select="Itinerary/bookingHeader/agency/zipCode"/>
												<br/>
												<xsl:value-of select="Itinerary/bookingHeader/agency/primaryPhone"/>
												<br/>
												<br/>
												<br/>
											</td>
											<td style="width:225px; " vAlign="top">
												<table border="0" style="font-size:12px" cellPadding="0" cellSpacing="0" width="225">
													<tbody>
														<tr>
															<td style="width:111px; ">
																<span>
																	<xsl:text>Booking Number</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:104px; ">
																<xsl:value-of select="Itinerary/bookingHeader/bookingNo"/>
															</td>
														</tr>
														<tr>
															<td style="width:111px; ">
																<span>
																	<xsl:text>Booking-date</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:104px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="Itinerary/bookingHeader/bookingDate"/>
																</xsl:call-template>																
															</td>
														</tr>
														<tr>
															<td style="width:111px; ">
																<span>
																	<xsl:text>Date of issue</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:104px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="Itinerary/bookingHeader/optionDate"/>
																</xsl:call-template>																
															</td>
														</tr>
														<tr>
															<td style="width:111px; ">
																<span>
																	<xsl:text>Departure-Date</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:104px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="Itinerary/bookingHeader/departureDate"/>
																</xsl:call-template>															
															</td>
														</tr>
														<tr>
															<td style="width:111px; ">
																<span>
																	<xsl:text>Booking status</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:104px; ">
																<xsl:value-of select="Itinerary/bookingHeader/bookingStatus"/>
															</td>
														</tr>
													</tbody>
												</table>
											</td>
											<td style="width:225px; " vAlign="top">
												<table border="0" style="font-size:12px" cellPadding="0" cellSpacing="0" width="225">
													<tbody>
														<tr>
															<td style="width:108px; ">
																<span>
																	<xsl:text>Deposit Date</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:104px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="Itinerary/bookingHeader/optionDate"/>
																</xsl:call-template>															
															</td>
														</tr>
														<tr>
															<td style="width:108px; ">
																<span>
																	<xsl:text>Deposit Due</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:107px; ">
																<span>
																	<xsl:text>$</xsl:text>
																</span>
																<xsl:call-template name="format-price">
																	<xsl:with-param name="price">
																		<xsl:value-of select="/Itinerary/bookingHeader/minimumAmount"/>
																	</xsl:with-param>
																</xsl:call-template>																
															</td>
														</tr>
														<tr>
															<td style="width:108px; ">
																<span>
																	<xsl:text>Paid to Date</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:107px; ">
																<span>
																	<xsl:text>$</xsl:text>
																</span>
																<xsl:call-template name="format-price">
																	<xsl:with-param name="price">
																		<xsl:value-of select="/Itinerary/bookingHeader/amountPaid"/>
																	</xsl:with-param>
																</xsl:call-template>																
															</td>
														</tr>
														<tr>
															<td style="width:108px; ">
																<span>
																	<xsl:text>Duration</xsl:text>
																</span>
															</td>
															<td style="width:10px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:107px; ">
																<xsl:value-of select="Itinerary/bookingHeader/tripDuration"/>
															</td>
														</tr>
													</tbody>
												</table>
											</td>
										</tr>										
										
									</tbody>
								</table>
								<xsl:if test="$isRFAExists='true'">
								<table width="675" style="font-size:12px" >
									<tbody>
										<tr align="center" style="font-weight:bold; ">
											<td width="675">
												<span>												
													<xsl:text>Hotel Request Pending - Booking is not yet confirmed</xsl:text>
												</span>	
											</td>										
										</tr>
										<tr align="center" style="font-weight:bold; ">
											<td width="675">												
												<xsl:text>Please Note: Pricing is not guaranteed until request is complete</xsl:text>
											</td>										
										</tr>										
									</tbody>
								</table>
								</xsl:if>
								<p>
									<span>
										<xsl:text>****IMPORTANT-PLEASE VERIFY ALL INFORMATION-IMPORTANT*****</xsl:text>
									</span>
								</p>
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<xsl:variable name="altova:CurrContextGrid_0DD0CC20" select="."/>
									<tbody>
										<tr>
											<td colspan="14" style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>Passenger Information</xsl:text>
												</span>
											</td>
										</tr>
										<tr style="background-color:#cacaca; font-weight:bold; text-align:center; ">
											<td colspan="5">
												<span>
													<xsl:text>Passenger(s)</xsl:text>
												</span>
											</td>
											<td>
												<span>
													<xsl:text>Age</xsl:text>
												</span>
											</td>
											<!--<td>
												<span>
													<xsl:text>Price</xsl:text>
												</span>
											</td>
											<td>
												<span>
													<xsl:text>Rental</xsl:text>
												</span>
											</td>
											<td>
												<span>
													<xsl:text>Apple Extras</xsl:text>
												</span>
											</td>
											<td>
												<span>
													<xsl:text>Insurance</xsl:text>
												</span>
											</td>
											<td>
												<span>
													<xsl:text>Fee</xsl:text>
												</span>
											</td>
											<td>
												<span>
													<xsl:text>Taxes</xsl:text>
												</span>
											</td>-->
											<td>
												<span>
													<xsl:text>Total</xsl:text>
												</span>
											</td>
											<!--<td>
												<span>
													<xsl:text>Status</xsl:text>
												</span>
											</td>-->
										</tr>
														<xsl:for-each select="Itinerary/guests/GuestInfo">
															<tr style="background-color:#f5f5f5; ">
																<td>
																	<xsl:value-of select="guestId"/>
																</td>
																<td>
																	<xsl:value-of select="title"/>
																</td>
																<td>
																	<xsl:value-of select="lastName"/>
																</td>
																<td>
																	<xsl:value-of select="firstName"/>
																</td>
																<td>
																	<xsl:value-of select="middleName"/>
																</td>
																<td>
																	<xsl:value-of select="age"/>
																</td>
																<!--<td>
																	<span>
																		<xsl:text>$</xsl:text>
																	</span>
																	<xsl:call-template name="format-price">
																		<xsl:with-param name="price">
																			<xsl:value-of select="priceBreakup/basePrice"/>
																		</xsl:with-param>
																	</xsl:call-template>																
																</td>
																<td>
																	<span>
																		<xsl:text>$</xsl:text>
																	</span>
																	<xsl:call-template name="format-price">
																		<xsl:with-param name="price">
																			<xsl:value-of select="priceBreakup/vehiclePrice"/>
																		</xsl:with-param>
																	</xsl:call-template>																
																</td>
																<td>
																	<span>
																		<xsl:text>$</xsl:text>
																	</span>
																	<xsl:call-template name="format-price">
																		<xsl:with-param name="price">
																			<xsl:value-of select="priceBreakup/servicePrice"/>
																		</xsl:with-param>
																	</xsl:call-template>																
																</td>
																<td>
																	<span>
																		<xsl:text>$</xsl:text>
																	</span>
																	<xsl:call-template name="format-price">
																		<xsl:with-param name="price">
																			<xsl:value-of select="priceBreakup/insurancePrice"/>
																		</xsl:with-param>
																	</xsl:call-template>																
																</td>
																<td>
																	<span>
																		<xsl:text>$</xsl:text>
																	</span>
																	<xsl:call-template name="format-price">
																		<xsl:with-param name="price">
																			<xsl:value-of select="priceBreakup/fees"/>
																		</xsl:with-param>
																	</xsl:call-template>																
																</td>
																<td>
																	<span>
																		<xsl:text>$</xsl:text>
																	</span>
																	<xsl:call-template name="format-price">
																		<xsl:with-param name="price">
																			<xsl:value-of select="priceBreakup/taxPrice"/>
																		</xsl:with-param>
																	</xsl:call-template>																
																</td>-->
																<td>
																	<span>
																		<xsl:text>$</xsl:text>
																	</span>
																	<xsl:call-template name="format-price">
																		<xsl:with-param name="price">
																			<xsl:value-of select="priceBreakup/totalPrice"/>
																		</xsl:with-param>
																	</xsl:call-template>																
																</td>
																<!--<td>
																	<xsl:value-of select="status"/>
																</td>-->
															</tr>
														</xsl:for-each>
									</tbody>
								</table>
<!-- 								<xsl:if test="not($promoCode = '')">  -->
<!-- 								<p align="left"> -->
<!-- 									<span> -->
<!-- 										<xsl:text>Prices Reflect Promotional Discount of $</xsl:text> -->
<!-- 									</span> -->
<!-- 									<xsl:call-template name="format-price"> -->
<!-- 										<xsl:with-param name="price"> -->
<!-- 											<xsl:value-of select="/Itinerary/bookingHeader/promoSaving"/> -->
<!-- 										</xsl:with-param> -->
<!-- 									</xsl:call-template>																 -->
<!-- 									<span> -->
<!-- 										<xsl:text> for Promotion Code: </xsl:text> -->
<!-- 									</span> -->
<!-- 													<span style="font-weight:bold; "> -->
<!-- 										<xsl:value-of select="/Itinerary/bookingHeader/promoCode"/> -->
<!-- 													</span> -->
<!-- 								</p> -->
<!-- 								</xsl:if> -->
								<p>
									<span>
										<xsl:text>*****PROPER PROOF OF CITIZENSHIP REQUIRED*****</xsl:text>
									</span>
									<br/>
								</p>
								<br/>
						<!--  For Flights -->
							<xsl:variable name="flightsExists">
								<xsl:call-template name="checkFlightsExists"/>
							</xsl:variable>
							<xsl:if test="$flightsExists='true'">
								<table border="0" cellPadding="2" cellSpacing="2" width="675">
									<tbody>
										<tr>
											<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>Your Flights</xsl:text>
												</span>
											</td>
										</tr>
									</tbody>
								</table>
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<tbody>
										<tr style="background-color:#cacaca; font-weight:bold; ">
											<td style="width:88px; " align="center">
												<span>
													<xsl:text>Type</xsl:text>
												</span>
											</td>
											<td style="width:77px; " align="center">
												<span>
													<xsl:text>Passenger(s)</xsl:text>
												</span>
											</td>
											<td style="width:97px; ">						
												<span>
													<xsl:text>Flight</xsl:text>
												</span>
											</td>
											
											<td style="width:120px; ">
												<span>
													<xsl:text>Depart</xsl:text>
												</span>
											</td>
											<td style="width:120px; ">
												<span>
													<xsl:text>Arrive</xsl:text>
												</span>
											</td>
											<td style="width:65px; " align="center">
												<span>
													<xsl:text>Fare Class</xsl:text>
												</span>
											</td>
											<td style="width:70px; " align="center">
												<span>
													<xsl:text>Aircraft Type</xsl:text>
												</span>
											</td>
										</tr>
									</tbody>
								</table>
					<xsl:for-each select="/Itinerary/packages/Package">
						<xsl:if test="selectedFlight">
							<xsl:call-template name="displayFlightDetails">
								<xsl:with-param name="tripFlight" select="selectedFlight"/>
							</xsl:call-template>											
						</xsl:if>
																								</xsl:for-each>
					<xsl:for-each select="/Itinerary/flights/TripFlight">
						<xsl:call-template name="displayFlightDetails">
							<xsl:with-param name="tripFlight" select="."/>
						</xsl:call-template>											
																						</xsl:for-each>
																				<br/>
				</xsl:if>
				<xsl:variable name="hotelsExists">
					<xsl:call-template name="checkHotelsExists"/>
				</xsl:variable>
				<xsl:if test="$hotelsExists='true'">
				<table border="0" cellPadding="2" cellSpacing="2" width="675">
					<tbody>
						<tr>
							<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
								<span style="font-weight:bold; ">
									<xsl:text>Hotel Information </xsl:text>
								</span>
								<span>
									<xsl:text>(per room)</xsl:text>
								</span>
							</td>
						</tr>
					</tbody>
				</table>
				<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
					<tbody>
						<tr style="background-color:#cacaca; font-weight:bold; ">
							<td style="width:86px; " align="center">
								<span>
									<xsl:text>Passenger(s)</xsl:text>
								</span>
							</td>
								<td style="width:168px; ">
								<span>
									<xsl:text>Hotel</xsl:text>
								</span>
							</td>
								<td style="width:169px; " align="center">
								<span>
										<xsl:text>Room</xsl:text>
								</span>
							</td>
								<td style="width:110px; ">
								<span>
									<xsl:text>Check-in</xsl:text>
								</span>
							</td>
								<td style="width:110px; ">
								<span>
									<xsl:text>Check-out</xsl:text>
								</span>
							</td>
							<td style="width:110px; ">
								<span>
									<xsl:text>Meal Type</xsl:text>
								</span>
							</td>
						</tr>
					</tbody>
					</table>							
						<xsl:for-each select="/Itinerary/packages/Package">
							<xsl:if test="selectedHotel">
								<xsl:call-template name="displayHotel">
									<xsl:with-param name="hotel" select="selectedHotel"/>
								</xsl:call-template>											
							</xsl:if>
						</xsl:for-each>
						<xsl:for-each select="/Itinerary/hotels/Hotel">
							<xsl:call-template name="displayHotel">
								<xsl:with-param name="hotel" select="."/>
							</xsl:call-template>											
						</xsl:for-each>	

																			<br/>
				</xsl:if>
				<!-- Vehicle display -->
				<xsl:variable name="vehiclesExists">
					<xsl:call-template name="checkVehiclesExists"/>
				</xsl:variable>
				<xsl:if test="$vehiclesExists='true'">
								<table border="0" cellPadding="2" cellSpacing="2" width="675">
					<tbody>
						<tr>
							<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
								<span style="font-weight:bold; ">
									<xsl:text>Car Information </xsl:text>
								</span>
							</td>
						</tr>
					</tbody>
				</table>
					<table style="font-size:12px" border="0" cellPadding="2" cellSpacing="2" width="675">
						<tbody>
							<tr style="background-color:#cacaca; font-weight:bold; ">
								<td style="width:86px; " align="center">
									<span>
										<xsl:text>Driver</xsl:text>
									</span>
								</td>
								<td style="width:70px; ">
									<span>
										<xsl:text>Company</xsl:text>
									</span>
								</td>
								<td style="width:188px; " align="center">
									<span>
										<xsl:text>Description</xsl:text>
									</span>
								</td>
								<td style="width:79px; ">
									<span>
										<xsl:text>Class</xsl:text>
									</span>
								</td>
								<td style="width:110px; ">
									<span>
										<xsl:text>Pick-up</xsl:text>
									</span>
								</td>
								<td style="width:110px; ">
									<span>
										<xsl:text>Drop-off</xsl:text>
									</span>
								</td>
							</tr>
							<xsl:for-each select="/Itinerary/packages/Package">
								<xsl:if test="selectedVehicle">
									<xsl:call-template name="displayVehicle">
										<xsl:with-param name="vehicle" select="selectedVehicle"/>
									</xsl:call-template>											
								</xsl:if>
							</xsl:for-each>
							<xsl:for-each select="/Itinerary/vehicles/Vehicle">
								<xsl:call-template name="displayVehicle">
									<xsl:with-param name="vehicle" select="."/>
								</xsl:call-template>											
							</xsl:for-each>
						</tbody>
					</table>				
					<br/>
				</xsl:if>				
								<!--  for services:begin -->
								<xsl:if test="(count($services/Service)>=1)">
								<table border="0" cellPadding="2" cellSpacing="2" width="675">
									<tbody>
										<tr>
											<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>Apple Extras</xsl:text>
												</span>
											</td>
										</tr>
									</tbody>
								</table>
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<tbody>
										<tr style="background-color:#cacaca; font-weight:bold; ">
											<td style="width:86px; " align="center">
												<span>
													<xsl:text>Passenger(s)</xsl:text>
												</span>
											</td>
											<td style="width:264px; ">
												<span>
													<xsl:text>Apple Extra</xsl:text>
												</span>
											</td>
											<td style="width:305px; ">
												<span>
													<xsl:text>Selected Date</xsl:text>
												</span>
											</td>
										</tr>
										<xsl:for-each select="Itinerary/services/Service">
															 <xsl:if test="serviceCode != 'SUP035' ">
															<tr>
																<td style="text-align:center; width:86px; ">
													<xsl:value-of select="guestAllocation"/>
																</td>
																<td style="width:264px; ">
													<xsl:value-of select="serviceName"/>
																</td>
																<td style="width:305px; ">
													<xsl:call-template name="FormatDateMMDDYYYY">
														<xsl:with-param name="DateTime" select="selectedDate"/>
													</xsl:call-template>
																</td>
															</tr>
														</xsl:if>
														</xsl:for-each>
									</tbody>
								</table>
								</xsl:if>
								<!-- for services:end-->
								<br/>
								<!--  for insurances: begin -->
								<xsl:if test="(count($insurances/Insurance)>=1)">
								<table border="0" cellPadding="2" cellSpacing="2" width="675">
									<xsl:variable name="altova:CurrContextGrid_0DD36A68" select="."/>
									<tbody>
										<tr>
											<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>AVOK - Total Vacation Security</xsl:text>
												</span>
											</td>
										</tr>
									</tbody>
								</table>
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<xsl:variable name="altova:CurrContextGrid_0DD36BE8" select="."/>
									<tbody>
										<tr style="background-color:#cacaca; font-weight:bold; ">
											<td style="width:86px; " align="center">
												<span>
													<xsl:text>Passenger(s)</xsl:text>
												</span>
											</td>
											<td style="width:264px; ">
												<span>
													<xsl:text>Vacation Security Type</xsl:text>
												</span>
											</td>
											<td style="width:305px; ">
												<span>
													<xsl:text> </xsl:text>
												</span>
											</td>
										</tr>
														<xsl:for-each select="/Itinerary/insurances/Insurance">
															<tr>
																<td style="text-align:center; width:86px; ">
																	<xsl:value-of select="guestAllocation"/>
																</td>
																<td style="text-align:left; width:264px; ">
																	<xsl:value-of select="materailDesc"/>
																</td>
																<td style="text-align:center; width:305px; ">
																	<a>
																		<xsl:choose>
																			<xsl:when test="substring(string(&apos;http://www.applevacations.com/avok&apos;), 1, 1) = '#'">
																				<xsl:attribute name="href">
																					<xsl:value-of select="&apos;http://www.applevacations.com/avok&apos;"/>
																				</xsl:attribute>
																			</xsl:when>
																			<xsl:otherwise>
																				<xsl:attribute name="href">
																					<xsl:if test="substring(string(&apos;http://www.applevacations.com/avok&apos;), 2, 1) = ':'">
																						<xsl:text>file:///</xsl:text>
																					</xsl:if>
																					<xsl:value-of select="translate(string(&apos;http://www.applevacations.com/avok&apos;), '&#x5c;', '/')"/>
																				</xsl:attribute>
																			</xsl:otherwise>
																		</xsl:choose>
																		<span>
																			<xsl:text>Coverage Details</xsl:text>
																		</span>
																	</a>
																</td>
															</tr>
														</xsl:for-each>
									</tbody>
								</table>
								<table align="" width="675">
										<tr>
											<td align="center" style="">
												<span style="">
													<xsl:text>Travelers should review the full details of the plan information for their state of residence by visiting www.tripmate.com/wpA430 or contacting Trip Mate directly at 866-389-5378 prior to purchasing the travel protection.</xsl:text>
												</span>
												
											</td>
										</tr>

									</table>
								</xsl:if>
								<!--  for insurances:end -->
								<br/>
								<br/>
								<!-- for paymenthistory:start -->
								<table border="0" cellPadding="2" cellSpacing="2" width="675">
									<tbody>
										<tr>
											<td
												style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>Payment History </xsl:text>
												</span>
											</td>
										</tr>
									</tbody>
								</table>
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<tbody>
										<tr style="background-color:#cacaca; font-weight:bold; ">
											<td style="width:86px; " align="center">
												<span>
													<xsl:text>Payment Date</xsl:text>
												</span>
											</td>	
											<td style="width:188px; " align="center">
												<span>
													<xsl:text>Payee Name</xsl:text>
												</span>
											</td>
											<td style="width:70px; " align="center">
												<span>
													<xsl:text>Amount</xsl:text>
												</span>
											</td>
											<td style="width:159px; " align="center">
												<span>
													<xsl:text>Payment Type</xsl:text>
												</span>
											</td>
											<td style="width:140px; " align="center">
												<span>
													<xsl:text>Method of Payment</xsl:text>
												</span>
											</td>
										</tr>
										<tr style="background-color:#f5f5f5; " vAlign="middle">
											<xsl:choose>
												<xsl:when test="(count(/Itinerary/bookingHeader/paymentHistoryInformationList/PaymentHistory)>=1)">
																<xsl:for-each select="/Itinerary/bookingHeader/paymentHistoryInformationList/PaymentHistory">
																<!-- inserting a new row to display Payment History  in proper orientation  -->
																<tr>
																		<td style="width:168px; ">															
																			<span>
																				<xsl:call-template name="FormatDateMMDDYYYY">
																					<xsl:with-param name="DateTime" select="paymentDate"/>
																				</xsl:call-template>																			
																			</span>													    														
																		</td>
																		<td style="width:168px; ">
																			<span>
																				<xsl:value-of select="firstName"/>
																				<xsl:text> </xsl:text>
																				<xsl:value-of select="lastName"/>
																			</span>
																		</td>
																		<td style="width:168px; ">
																			<span>
																				<xsl:text>$</xsl:text>
																				<xsl:call-template name="format-price">
																					<xsl:with-param name="price">
																						<xsl:value-of select="amountPaid"/>
																					</xsl:with-param>
																				</xsl:call-template>																				
																				<xsl:text> </xsl:text>
																				<xsl:value-of select="sign"/>																				
																			</span>														
																		</td>
																		<td style="width:168px; ">															
																			<span>
																				<xsl:value-of select="paymentMode"/>
																			</span>														    														
																		</td>
																		<td style="width:168px; ">
																			<span>
																				<xsl:value-of select="instrNo"/>
																			</span>															
																		</td>
																		</tr> 
															</xsl:for-each>
												</xsl:when>
												<xsl:otherwise>
													<td colspan="5">No payments have been made on this booking.</td>
												</xsl:otherwise>
											</xsl:choose>										
										</tr>
									</tbody>
								</table><!-- for paymenthistory:end -->
								<br />
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<xsl:variable name="altova:CurrContextGrid_0DD37188" select="."/>
									<tbody>
										<tr>
											<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>Notices</xsl:text>
												</span>
											</td>
										</tr>
										<xsl:if test="(count(/Itinerary/notices/Alert)>=1)">										
										<tr>
											<td>
												<span>
													<xsl:for-each select="/Itinerary/notices/Alert">													
														<xsl:value-of select="alertMessage"/>
														<xsl:text> </xsl:text>
													</xsl:for-each>
												</span>
											</td>
										</tr>
										</xsl:if>
										<tr>
											<td>
												<span>
													<xsl:text>This booking is subject to the Terms &amp; Conditions of the Apple Vacations
													Fair Trade Contract which can be viewed at </xsl:text>
													<a href="http://www.applevacations.com/ftc" target="_blank">http://www.applevacations.com/ftc</a>
													<xsl:text>
													Meals: Only hotels noted as "all inclusive or "Unlimited Luxury" include your meals and	
													beverages . If you did not purchase one of these hotels, please review the meal plan	
													purchased, if any, before you travel
													</xsl:text>	
												</span>
											</td>
										</tr>
									</tbody>
								</table>
								<br/>
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<xsl:variable name="altova:CurrContextGrid_0DD373C8" select="."/>
									<tbody>
										<tr>
											<td style="background-color:#005e9d; color:#ffffff; font-size:15px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>Price Breakdown</xsl:text>
												</span>
											</td>
										</tr>
									</tbody>
								</table>
								<table border="0" style="font-size:12px" cellPadding="0" cellSpacing="0" width="675">
									<xsl:variable name="altova:CurrContextGrid_0DD37548" select="."/>
									<tbody>
										<tr align="left">
											<td style="width:10px; ">
												<span>
													<xsl:text> </xsl:text>
												</span>
											</td>
											<td style="width:151px; ">
												<span>
													<xsl:text>Gross Total</xsl:text>
												</span>
											</td>
											<td style="width:10px; ">
												<span>
													<xsl:text>:</xsl:text>
												</span>
											</td>
											<td style="width:128px; ">
												<span>
													<xsl:text>$</xsl:text>
												</span>
												<xsl:call-template name="format-price">
													<xsl:with-param name="price">
														<xsl:value-of select="/Itinerary/bookingHeader/tourPrice"/>
													</xsl:with-param>
												</xsl:call-template>																
											</td>
											<td rowspan="6" style="width:451px; ">
												<xsl:if test="/Itinerary/bookingHeader/bookingStatus != 'PIF'">
												<table style="background-color:#f5f5f5; border-bottom:#a0a0a4 1px solid; border-left:#a0a0a4 1px solid; border-right:#a0a0a4 1px solid; border-top:#a0a0a4 1px solid; font-size:12px; " align="center" border="0" cellPadding="2" cellSpacing="2" width="320">
													<xsl:variable name="altova:CurrContextGrid_0DD37AE8" select="."/>
													<tbody>
													<xsl:choose>
														<xsl:when test="/Itinerary/bookingHeader/minimumAmount != '0.0' and /Itinerary/bookingHeader/amountDue != '0.0'">
														<tr style="font-weight:bold; ">
															<td style="width:146px; ">
																<span>
																	<xsl:text>Deposit of</xsl:text>
																</span>
															</td>
															<td style="width:8px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:144px; ">
																<span>
																	<xsl:text>$</xsl:text>
																</span>
																<xsl:call-template name="format-price">
																	<xsl:with-param name="price">
																		<xsl:value-of select="/Itinerary/bookingHeader/minimumAmount"/>
																	</xsl:with-param>
																</xsl:call-template>																
															</td>
														</tr>
														<tr style="font-weight:bold; ">
															<td style="width:146px; ">
																<span>
																	<xsl:text>Due by</xsl:text>
																</span>
															</td>
															<td style="width:8px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:144px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="/Itinerary/bookingHeader/optionDate"/>
																</xsl:call-template>															
															</td>
														</tr>
														<tr style="font-weight:bold; ">
															<td style="width:146px; ">
																<span>
																	<xsl:text>Balance Due By</xsl:text>
																</span>
															</td>
															<td style="width:8px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:144px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="/Itinerary/bookingHeader/finalDueDate"/>
																</xsl:call-template>															
															</td>
														</tr>
														</xsl:when>
														<xsl:when test="/Itinerary/bookingHeader/minimumAmount > 0">
															<tr style="font-weight:bold; ">
															<td style="width:146px; ">
																<span>
																	<xsl:text>Deposit of</xsl:text>
																</span>
															</td>
															<td style="width:8px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:144px; ">
																<span>
																	<xsl:text>$</xsl:text>
																</span>
																<xsl:call-template name="format-price">
																	<xsl:with-param name="price">
																		<xsl:value-of select="/Itinerary/bookingHeader/minimumAmount"/>
																	</xsl:with-param>
																</xsl:call-template>																
															</td>
														</tr>
														<tr style="font-weight:bold; ">
															<td style="width:146px; ">
																<span>
																	<xsl:text>Due by</xsl:text>
																</span>
															</td>
															<td style="width:8px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:144px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="/Itinerary/bookingHeader/optionDate"/>
																</xsl:call-template>															
															</td>
														</tr>
														</xsl:when>
														<xsl:when test="(/Itinerary/bookingHeader/tourPrice - /Itinerary/bookingHeader/amountPaid) != '0.0'">
														<tr style="font-weight:bold; ">
															<td style="width:146px; ">
																<span>
																	<xsl:text>Balance Due</xsl:text>
																</span>
															</td>
															<td style="width:8px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:144px; ">
																<span>
																	<xsl:text>$</xsl:text>
																</span>
																<xsl:call-template name="format-price">
																	<xsl:with-param name="price">
																		<xsl:value-of select="/Itinerary/bookingHeader/tourPrice - /Itinerary/bookingHeader/amountPaid"/>
																	</xsl:with-param>
																</xsl:call-template>																
															</td>
														</tr>
														<tr style="font-weight:bold; ">
															<td style="width:146px; ">
																<span>
																	<xsl:text>Balance Due By</xsl:text>
																</span>
															</td>
															<td style="width:8px; ">
																<span>
																	<xsl:text>:</xsl:text>
																</span>
															</td>
															<td style="width:144px; ">
																<xsl:call-template name="FormatDateMMDDYYYY">
																	<xsl:with-param name="DateTime" select="/Itinerary/bookingHeader/finalDueDate"/>
																</xsl:call-template>															
															</td>
														</tr>	
														</xsl:when>
														</xsl:choose>
													</tbody>
												</table>
												</xsl:if>
											</td>
										</tr>
										<!-- <tr>
											<td style="width:10px; ">
												<span>
													<xsl:text> </xsl:text>
												</span>
											</td>
											<td style="width:151px; ">
												<span>
													<xsl:text>Taxes</xsl:text>
												</span>
											</td>
											<td style="width:10px; ">
												<span>
													<xsl:text>:</xsl:text>
												</span>
											</td>
											<td style="width:128px; ">
												<span>
													<xsl:text>$</xsl:text>
												</span>
												<xsl:call-template name="format-price">
													<xsl:with-param name="price">
														<xsl:value-of select="/Itinerary/itineraryPrice/totalTax"/>
													</xsl:with-param>
												</xsl:call-template>
											</td>
										</tr> -->
										<tr>
											<td style="width:10px; ">
												<span>
													<xsl:text> </xsl:text>
												</span>
											</td>
											<td style="width:151px; ">
												<span>
													<xsl:text>Payments to Date</xsl:text>
												</span>
											</td>
											<td style="width:10px; ">
												<span>
													<xsl:text>:</xsl:text>
												</span>
											</td>
											<td style="width:128px; ">
												<span>
													<xsl:text>$</xsl:text>
												</span>
												<xsl:call-template name="format-price">
													<xsl:with-param name="price">
														<xsl:value-of select="/Itinerary/bookingHeader/amountPaid"/>
													</xsl:with-param>
												</xsl:call-template>																
											</td>
										</tr>
									</tbody>
								</table>
								<br/>
								<br/>
																<!-- For support Item #3622393 Start-->
								<xsl:if test="not($promoId = '')">
								<p align="left">
									<span>
										<xsl:text>Please note, Prices Reflect Promotional Discount of $</xsl:text>
									</span>
									<xsl:call-template name="format-price">
										<xsl:with-param name="price">
											<xsl:value-of select="/Itinerary/bookingHeader/promoSaving"/>
										</xsl:with-param>
									</xsl:call-template>																
									<span>
										<xsl:text> for Promotion Code: </xsl:text>
									</span>
									<span style="font-weight:bold; ">
									<xsl:value-of select="/Itinerary/bookingHeader/promoId"/>
									</span>
								</p>
							</xsl:if>
							<!-- For support Item #3622393 End-->
							</td>
						</tr>
					</tbody>
				</table>
			</body>
		</html>
	</xsl:template>
	<xsl:template name="agentName">
		<xsl:param name="agentFullName"/>
		<xsl:param name="agentFirstName"/>
		<xsl:param name="agentLastName"/>
		<xsl:choose>
			<xsl:when test="$agentFullName='New Agent'">
				<xsl:value-of select="concat($agentFirstName,'',$agentLastName)"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$agentFullName"/>
			</xsl:otherwise>
		</xsl:choose>	
	</xsl:template>
	<xsl:template name="format-price">
	  <xsl:param name="price"/>
	  <xsl:value-of	select="format-number($price, '#,##0.00')"/>
	</xsl:template>		
	<xsl:template name="checkFlightsExists">
		<xsl:choose>
			<xsl:when test="count(/Itinerary/flights/TripFlight) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:when test="count(/Itinerary/packages/Package/selectedFlight) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>false</xsl:text>
			</xsl:otherwise>			
		</xsl:choose>
	</xsl:template>	
	<xsl:template name="displayFlightDetails">
		<xsl:param name="tripFlight"/>
		<xsl:call-template name="displayFlight">
			<xsl:with-param name="flight" select="$tripFlight/outboundFlight"/>
			<xsl:with-param name="direction">O</xsl:with-param>
			<xsl:with-param name="guestAllocation" select="$tripFlight/guestAllocation"/>
		</xsl:call-template>
		<xsl:if test="$tripFlight/inboundFlight">
			<xsl:call-template name="displayFlight">
				<xsl:with-param name="flight" select="$tripFlight/inboundFlight"/>
				<xsl:with-param name="direction">I</xsl:with-param>
				<xsl:with-param name="guestAllocation" select="$tripFlight/guestAllocation"/>
			</xsl:call-template>
		</xsl:if>
	</xsl:template>
	<xsl:template name="displayFlight">
		<xsl:param name="flight"/>
		<xsl:param name="direction"/>
		<xsl:param name="guestAllocation"/>
		<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
			<tbody>
				<xsl:for-each select="$flight/flightSegments/FlightSegment">
					<tr style="background-color:#f5f5f5; " align="center" vAlign="middle">
						<xsl:if test="position() = 1">
						<td style="width:88px; ">
							<xsl:attribute name="rowspan">
								<xsl:value-of select="$flight/noOfStops + 1"/>
							</xsl:attribute>
							<span style="font-weight:bold; ">
								<xsl:choose>
									<xsl:when test="$direction='O'">
										<xsl:text>Departing </xsl:text>
									</xsl:when>
									<xsl:otherwise>
										<xsl:text>Returning </xsl:text>
									</xsl:otherwise>
								</xsl:choose>
								<xsl:text>Flight(s):</xsl:text>
							</span>
							<br/>
							<xsl:variable name="stops" select="$flight/noOfStops" />
							<xsl:choose>
								<xsl:when test="not($stops='0')">
									<xsl:value-of select="$stops" />
									<span>
										<xsl:text> Connection(s)</xsl:text>
									</span>
								</xsl:when>
								<xsl:otherwise>
									 Non Stop
								</xsl:otherwise>
							</xsl:choose>
							<br/>
						</td>
						<td style="width:77px; ">
							<xsl:attribute name="rowspan">
								<xsl:value-of select="$flight/noOfStops + 1"/>
							</xsl:attribute>				
							<xsl:value-of select="$guestAllocation"/>
						</td>
						</xsl:if>
						<td style="width:97px; ">
						<xsl:variable name="codeShareCarrier" select="codeShareCarrier" />
						<xsl:variable name="flightNo" select="flightNo" />						
							<xsl:choose>
								<xsl:when test="count(codeShareCarrier)>0">								
										<xsl:value-of select="carrier/carrierName" />
											
												<span>
													<xsl:text> #</xsl:text>
												 </span>	
												 <xsl:value-of select="$flightNo"/>	
												 <br/>										
												<span>
													<xsl:text> *Operated by </xsl:text>
												 </span>							
										<xsl:value-of select="codeShareCarrier/carrierName" />									
								</xsl:when>
								<xsl:otherwise>
												<xsl:value-of select="carrier/carrierName"/>
												 <span>
													<xsl:text> #</xsl:text>
												 </span>	
												 <xsl:value-of select="$flightNo"/>	
								</xsl:otherwise>
							</xsl:choose>
							<br/>													
								<xsl:if test="count(recordLocator)>0">									
									<span>
										<xsl:text> Record Locator </xsl:text>
									</span>						   
									<xsl:value-of select="recordLocator"/>
								</xsl:if>																													
						</td>
						<td style="width:120px; ">						
							<span style="font-weight:bold; ">
								<xsl:call-template name="FormatDateMMDDYYYYHHMM">
									<xsl:with-param name="DateTime" select="departureDate"/>
								</xsl:call-template>
							</span>
							<br/>
							<span style="font-weight:bold; ">
								<xsl:value-of select="gateway"/>
							</span>
						</td>
						<td style="width:120px; ">
							<span style="font-weight:bold; ">
								<xsl:call-template name="FormatDateMMDDYYYYHHMM">
									<xsl:with-param name="DateTime" select="arrivalDate"/>
								</xsl:call-template>
							</span>
							<br/>
							<span style="font-weight:bold; ">
								<xsl:value-of select="destination"/>
							</span>
						</td>
						<td style="width:65px; ">
							<span style="font-weight:bold; ">
								<xsl:value-of select="classOfService"/>
							</span>
						</td>
						<td style="width:70px; ">
							<xsl:value-of select="aircraftType"/>
						</td>
					</tr>
				</xsl:for-each>
			</tbody>
		</table>
	</xsl:template>
	<xsl:template name="checkHotelsExists">
		<xsl:choose>
			<xsl:when test="count(/Itinerary/hotels/Hotel) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:when test="count(/Itinerary/packages/Package/selectedHotel) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>false</xsl:text>
			</xsl:otherwise>			
		</xsl:choose>
	</xsl:template>	
	<xsl:template name="displayHotel">
		<xsl:param name="hotel"/>
		<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
		<tbody>
		<tr>
			<td style="text-align:center; width:86px; ">
				<xsl:value-of select="$hotel/displayRoomCategory/displayRoomPrice/guestAllocation"/>
			</td>			
			<td style="width:168px; ">
				<xsl:value-of select="$hotel/hotelName"/>
			</td>
			<td style="text-align:center;width:169px; ">
				<xsl:value-of select="$hotel/displayRoomCategory/roomTypeDescription"/>
			</td>
			<td style="width:110px; ">
				<xsl:call-template name="FormatDateMMDDYYYY">
					<xsl:with-param name="DateTime" select="$hotel/checkInDate"/>
				</xsl:call-template>
			</td>
			<td style="width:110px; ">
				<xsl:call-template name="FormatDateMMDDYYYY">
					<xsl:with-param name="DateTime" select="$hotel/checkOutDate"/>
				</xsl:call-template>
			</td>
			<td style="width:110px; ">
				<xsl:value-of select="$hotel/roomCategories/RoomCategory/mealplanDesc"/>	
			</td>
		</tr>
		</tbody>
		</table>
		<xsl:if test="$hotel/displayRoomCategory/status='Q'">
			<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
			  	<tbody>							
					<tr align="center" style="font-weight:bold; ">
						<td width="675">	
							<span>												
								<xsl:text>Room Category above is not yet confirmed</xsl:text>
							</span>	
						</td>										
					</tr>
				</tbody>
			</table>							 					
		</xsl:if>
	</xsl:template>
	<xsl:template name="checkVehiclesExists">
		<xsl:choose>
			<xsl:when test="count(/Itinerary/vehicles/Vehicle) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:when test="count(/Itinerary/packages/Package/selectedVehicle) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>false</xsl:text>
			</xsl:otherwise>			
		</xsl:choose>
	</xsl:template>
	<xsl:template name="checkRFAExists">
		<xsl:choose>
			<xsl:when test="count(/Itinerary/hotels/Hotel) > 0">
				<xsl:for-each select="/Itinerary/hotels/Hotel">
					<xsl:if test="displayRoomCategory/status='Q'">
						<xsl:text>true</xsl:text>
					</xsl:if>										
				</xsl:for-each>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>false</xsl:text>
			</xsl:otherwise>			
		</xsl:choose>
	</xsl:template>	
	<xsl:template name="displayVehicle">
		<xsl:param name="vehicle"/>
		<tr>
			<td style="text-align:center; width:86px; ">
				<xsl:value-of select="$vehicle/guestAllocation"/>
			</td>
			<td style="width:70px; ">
				<xsl:value-of select="$vehicle/companyDescription"/>
			</td>
			<td style="width:188px; ">
				<xsl:value-of select="$vehicle/description"/>
			</td>
			<td style="width:79px; ">
				<xsl:value-of select="$vehicle/vehicleClass"/>
			</td>
			<td style="width:110px; ">
				<xsl:value-of select="$vehicle/pickupLocation"/>
				<br/>
				<xsl:call-template name="FormatDateMMDDYYYYHHMM">
					<xsl:with-param name="DateTime" select="$vehicle/pickupTime"/>
				</xsl:call-template>
			</td>
			<td style="width:110px; ">
				<xsl:value-of select="$vehicle/dropOffLocation"/>
				<br/>
				<xsl:call-template name="FormatDateMMDDYYYYHHMM">
					<xsl:with-param name="DateTime" select="$vehicle/dropOffTime"/>
				</xsl:call-template>
			</td>
		</tr>
	</xsl:template>
    <xsl:template name="FormatDateMMDDYYYYHHMM">
	    <xsl:param name="DateTime" />
	    <!-- new date format 2010-10-13 00:00:00.0 EDT -->
	    <xsl:variable name="year">
	      <xsl:value-of select="substring($DateTime,1,4)" />
	    </xsl:variable>
	    <xsl:variable name="mo">
	      <xsl:value-of select="substring($DateTime,6,2)" />
	    </xsl:variable>
	    <xsl:variable name="day">
	      <xsl:value-of select="substring($DateTime,9,2)" />
	    </xsl:variable>
	    <xsl:variable name="hh">
	      <xsl:value-of select="substring($DateTime,12,2)" />
	    </xsl:variable>
	    <xsl:variable name="mm">
	      <xsl:value-of select="substring($DateTime,15,2)" />
	    </xsl:variable>
	    <xsl:variable name="ss">
	      <xsl:value-of select="substring($DateTime,18,2)" />
	    </xsl:variable>
	    <xsl:value-of select="$mo"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$day"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$year"/>
	    <xsl:text> </xsl:text>
	    <xsl:choose>
	    	<xsl:when test="$hh='00'">
	    		<xsl:text>12</xsl:text>
	    	</xsl:when>
	    	<xsl:when test="$hh &gt; '12'">
	    		<xsl:value-of select="number($hh) - 12"/>
	    	</xsl:when>
	    	<xsl:otherwise>
	    		<xsl:value-of select="$hh"/>
	    	</xsl:otherwise>
	    </xsl:choose>	    
	    <xsl:text>:</xsl:text>
	    <xsl:value-of select="$mm"/>
	    <xsl:text> </xsl:text>
	    <xsl:choose>
	    	<xsl:when test="$hh &lt; '12'">
	    		<xsl:text>AM</xsl:text>
	    	</xsl:when>
	    	<xsl:otherwise>
	    		<xsl:text>PM</xsl:text>
	    	</xsl:otherwise>
	    </xsl:choose>
	</xsl:template>
    <xsl:template name="FormatDateMMDDYYYY">
	    <xsl:param name="DateTime" />
	    <!-- new date format 2010-10-13 00:00:00.0 EDT -->
	    <xsl:variable name="year">
	      <xsl:value-of select="substring($DateTime,1,4)" />
	    </xsl:variable>
	    <xsl:variable name="mo">
	      <xsl:value-of select="substring($DateTime,6,2)" />
	    </xsl:variable>
	    <xsl:variable name="day">
	      <xsl:value-of select="substring($DateTime,9,2)" />
	    </xsl:variable>
	    <xsl:variable name="hh">
	      <xsl:value-of select="substring($DateTime,12,2)" />
	    </xsl:variable>
	    <xsl:variable name="mm">
	      <xsl:value-of select="substring($DateTime,15,2)" />
	    </xsl:variable>
	    <xsl:variable name="ss">
	      <xsl:value-of select="substring($DateTime,18,2)" />
	    </xsl:variable>
	    <xsl:value-of select="$mo"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$day"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$year"/>
	</xsl:template>
</xsl:stylesheet>
