<?xml version="1.0" encoding="UTF-8"?>
	<!--
		Designed and generated by Altova StyleVision Enterprise Edition 2010
		rel. 3 - see http://www.altova.com/stylevision for more information.
	-->
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:clitype="clitype"
	xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
	xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java"
	xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi"
	xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:altova="http://www.altova.com"
	exclude-result-prefixes="clitype fn iso4217 ix java link xbrldi xbrli xlink xs xsi altova">
	<xsl:output version="4.0" method="html" indent="no"
		encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"
		doctype-system="http://www.w3.org/TR/html4/loose.dtd" />
	<xsl:param name="SV_OutputFormat" select="'HTML'" />
	<xsl:variable name="XML" select="/" />
	<xsl:variable name="packages" select="/Itinerary/packages" />
	<xsl:variable name="flights" select="/Itinerary/flights" />
	<xsl:variable name="hotels" select="/Itinerary/hotels" />
	<xsl:variable name="insurances" select="/Itinerary/insurances" />
	<xsl:variable name="services" select="/Itinerary/services" />
	<xsl:variable name="promoCode" select="/Itinerary/bookingHeader/promoCode" />
	<xsl:template match="/">
		<html>
			<head>
				<title>
					<xsl:text> </xsl:text>
				</title>
				<meta http-equiv="X-UA-Compatible" content="IE=7" />
				<xsl:comment>[if
					IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.60in; margin-right:0.60in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<table style="background-color:#ffffff; border-bottom:#a0a0a4 2px solid; border-left:#a0a0a4 2px solid; border-right:#a0a0a4 2px solid; border-top:#a0a0a4 2px solid; font-family:arial , helvetica , sans-serif; font-size:12px; " border="0" cellPadding="10" cellSpacing="0" width="675">
					<xsl:variable name="altova:CurrContextGrid_0BE6D380" select="."/>
					<tbody>
						<tr style="height:40px; ">
							<td style="width:405px; " vAlign="top">
								<img>
									<xsl:attribute name="src">
											<xsl:text>http://www.applevacations.com/appleweb/images/abe/avlogo.gif</xsl:text>
									</xsl:attribute>
									<xsl:attribute name="alt"/>
								</img>
							</td>
							<td style="color:#005e9d; font-size:14px; width:345px; " align="right" vAlign="top">
								<span>
									<xsl:text>Room Above Allotment Request</xsl:text><br/>									
								</span>								
							</td>
						</tr>						
						
						<tr>													
							<td colspan="2" style="width:405px; ">																
								<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
									<xsl:variable name="altova:CurrContextGrid_0DD0CC20" select="."/>
									<tbody>
										<tr>
											<td colspan="14" >
											 	<xsl:for-each select="/Itinerary/hotels/Hotel">	
													<span style="font-weight:bold; ">
														<xsl:text>To:	</xsl:text>
    												</span>
														<xsl:value-of select="vendor/email"/>
														<xsl:text>/</xsl:text>
														<xsl:value-of select="vendor/faxNo"/>
												</xsl:for-each>		
													<br/>
													<span style="font-weight:bold; ">
														<xsl:text>From:	</xsl:text>
													</span>	
														<xsl:value-of select="/Itinerary/rfaFromEmailAddress"/>
														<xsl:text>/</xsl:text>
														<xsl:value-of select="/Itinerary/rfaFromFaxNumber"/>
													
													<br/>
													<span style="font-weight:bold; ">
														<xsl:text>RE:  </xsl:text>
													</span>
														<xsl:text>Room Request</xsl:text>												
												<br/>	
												<br/>
												<span>
													<xsl:text>Dear Travel Partner,</xsl:text>
												</span>
												<br/>
												<br/>
												<span>
													<xsl:text>Apple Vacations has received a request for a room no longer available in our inventory.  Can you please confirm a room above Apple Vacations allotment for the dates, configuration and room category listed below? </xsl:text>
												</span>
												<br/>
												<br/>
												<span>
													<xsl:text>Please respond to hotelrequest@applevac.com via email to confirm/deny this request inclusive of any confirmation numbers. If you have questions or concerns regarding this request, please contact our Customer Service department at 1 800-365-2775 ext 5282 between (8:30am to 7:00pm CST).</xsl:text>
												</span>
												<br/>
												<br/>
												<span>
													<xsl:text>Regards,</xsl:text>
												</span>
												<br/>
												<br/>
												<span style="font-weight:bold; ">
													<xsl:text>Apple Vacations</xsl:text>
												</span>
												<br/>
												<span style="font-weight:bold; ">
													<xsl:text>Reservations Department</xsl:text>
												</span>							
											</td>							
										</tr>
										<br/>
										<br/>
										<tr></tr>
										<tr></tr>										
										<tr>
											<td colspan="14" style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
												<span style="font-weight:bold; ">
													<xsl:text>Passenger Information</xsl:text>
												</span>
											</td>
										</tr>
										<tr style="background-color:#cacaca; font-weight:bold; text-align:center; ">
											<td colspan="5">
												<span>
													<xsl:text>Passenger(s)</xsl:text>
												</span>
											</td>
											<td>
												<span>
													<xsl:text>Age</xsl:text>
												</span>
											</td>																																
										</tr>
										<xsl:for-each select="Itinerary/guests/GuestInfo">
											<tr style="background-color:#f5f5f5; ">
												<td>
													<xsl:value-of select="guestId"/>
												</td>
												<td>
													<xsl:value-of select="title"/>
												</td>
												<td>
													<xsl:value-of select="lastName"/>
												</td>
												<td>
													<xsl:value-of select="firstName"/>
												</td>
												<td>
													<xsl:value-of select="middleName"/>
												</td>
												<td>
													<xsl:value-of select="age"/>
												</td>																																								
											</tr>
										</xsl:for-each>
									</tbody>
								</table>
															
				<xsl:variable name="hotelsExists">
					<xsl:call-template name="checkHotelsExists"/>
				</xsl:variable>
				<xsl:if test="$hotelsExists='true'">
				<table border="0" cellPadding="2" cellSpacing="2" width="675">
					<tbody>
						<tr>
							<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
								<span style="font-weight:bold; ">
									<xsl:text>Hotel Information </xsl:text>
								</span>
								<span>
									<xsl:text>(per room)</xsl:text>
								</span>
							</td>
						</tr>
					</tbody>
				</table>
				<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
					<tbody>
						<tr style="background-color:#cacaca; font-weight:bold; ">
							<td style="width:86px; " align="center">
								<span>
									<xsl:text>Number of rooms being requested</xsl:text>
								</span>
							</td>
								<td style="width:168px; ">
								<span>
									<xsl:text>Hotel Name</xsl:text>
								</span>
							</td>
								<td style="width:169px; " align="center">
								<span>
										<xsl:text>Room Category</xsl:text>
								</span>
							</td>
								<td style="width:110px; ">
								<span>
									<xsl:text>Check-in</xsl:text>
								</span>
							</td>
								<td style="width:110px; ">
								<span>
									<xsl:text>Check-out</xsl:text>
								</span>
							</td>
							<td style="width:110px; ">
								<span>
									<xsl:text>Dates required above allotment</xsl:text>
								</span>
							</td>
						</tr>
							<!-- <xsl:for-each select="/Itinerary/packages/Package">
								<xsl:if test="selectedHotel">
									<xsl:call-template name="displayHotel">
										<xsl:with-param name="hotel" select="selectedHotel"/>
									</xsl:call-template>											
								</xsl:if>
							</xsl:for-each> -->
							<xsl:for-each select="/Itinerary/reqDatesForAvl/com.kcdata.abe.data.dto.RequestedDatesForAvailability">											
								<xsl:call-template name="displayHotel">
									<xsl:with-param name="hotel" select="/Itinerary/hotels/Hotel"/>
									<xsl:with-param name="requestedDatesForAvailability" select="."/>
								</xsl:call-template>							
							</xsl:for-each>											
					</tbody>
				</table>
				<br/>				
				</xsl:if>
				<table border="0" cellPadding="2" cellSpacing="2" width="675">
					<tbody>
						<tr>
							<td style="background-color:#005e9d; color:#ffffff; font-size:12px; padding-left:5px; ">
								<span style="font-weight:bold; ">
									<xsl:text>Apple Vacations Booking Number </xsl:text>
								</span>								
							</td>
						</tr>
					</tbody>
				</table>
				<br/>
				<table border="0" style="font-size:12px" cellPadding="2" cellSpacing="2" width="675">
					<tbody>
						<tr style="background-color:#cacaca; font-weight:bold; ">
							<td style="width:86px; " align="left">
								<span>
									<xsl:value-of select="/Itinerary/bookingNo"/>
								</span>
							</td>								
						</tr>						
					</tbody>
				</table>																							
				</td>
				</tr>
				</tbody>
				</table>
			</body>
		</html>
	</xsl:template>
	
	<xsl:template name="format-price">
	  <xsl:param name="price"/>
	  <xsl:value-of	select="format-number($price, '#,##0.00')"/>
	</xsl:template>		
		
	
	
	<xsl:template name="checkHotelsExists">
		<xsl:choose>
			<xsl:when test="count(/Itinerary/hotels/Hotel) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:when test="count(/Itinerary/packages/Package/selectedHotel) > 0">
				<xsl:text>true</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>false</xsl:text>
			</xsl:otherwise>			
		</xsl:choose>
	</xsl:template>	
	<xsl:template name="displayHotel">
		<xsl:param name="hotel"/>
		<xsl:param name="requestedDatesForAvailability"/>
		<tr>
			<td style="text-align:center; width:86px; ">
				<!-- <xsl:value-of select="$hotel/noOfRequestedRooms"/> -->
				<xsl:value-of select="$requestedDatesForAvailability/noOfRooms"/>
			</td>
			<td style="width:168px; ">
				<xsl:value-of select="$hotel/hotelName"/>
			</td>
			<td style="text-align:center;width:169px; ">
				<xsl:value-of select="$requestedDatesForAvailability/roomDescription"/>
			</td>
			<td style="width:110px; ">
				<xsl:call-template name="FormatDateMMDDYYYY">
					<xsl:with-param name="DateTime" select="$hotel/checkInDate"/>
				</xsl:call-template>
			</td>
			<td style="width:110px; ">
				<xsl:call-template name="FormatDateMMDDYYYY">
					<xsl:with-param name="DateTime" select="$hotel/checkOutDate"/>
				</xsl:call-template>
			</td>
			<td style="width:110px; ">
				<xsl:for-each select="$requestedDatesForAvailability/reqDates/string">			
				 <xsl:value-of select="."/>
				 <xsl:text>,</xsl:text>
				 <br></br>
				</xsl:for-each>				
			</td>
		</tr>
	</xsl:template>		
    <xsl:template name="FormatDateMMDDYYYYHHMM">
	    <xsl:param name="DateTime" />
	    <!-- new date format 2010-10-13 00:00:00.0 EDT -->
	    <xsl:variable name="year">
	      <xsl:value-of select="substring($DateTime,1,4)" />
	    </xsl:variable>
	    <xsl:variable name="mo">
	      <xsl:value-of select="substring($DateTime,6,2)" />
	    </xsl:variable>
	    <xsl:variable name="day">
	      <xsl:value-of select="substring($DateTime,9,2)" />
	    </xsl:variable>
	    <xsl:variable name="hh">
	      <xsl:value-of select="substring($DateTime,12,2)" />
	    </xsl:variable>
	    <xsl:variable name="mm">
	      <xsl:value-of select="substring($DateTime,15,2)" />
	    </xsl:variable>
	    <xsl:variable name="ss">
	      <xsl:value-of select="substring($DateTime,18,2)" />
	    </xsl:variable>
	    <xsl:value-of select="$mo"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$day"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$year"/>
	    <xsl:text> </xsl:text>
	    <xsl:choose>
	    	<xsl:when test="$hh='00'">
	    		<xsl:text>12</xsl:text>
	    	</xsl:when>
	    	<xsl:when test="$hh &gt; '12'">
	    		<xsl:value-of select="number($hh) - 12"/>
	    	</xsl:when>
	    	<xsl:otherwise>
	    		<xsl:value-of select="$hh"/>
	    	</xsl:otherwise>
	    </xsl:choose>	    
	    <xsl:text>:</xsl:text>
	    <xsl:value-of select="$mm"/>
	    <xsl:text> </xsl:text>
	    <xsl:choose>
	    	<xsl:when test="$hh &lt; '12'">
	    		<xsl:text>AM</xsl:text>
	    	</xsl:when>
	    	<xsl:otherwise>
	    		<xsl:text>PM</xsl:text>
	    	</xsl:otherwise>
	    </xsl:choose>
	</xsl:template>
    <xsl:template name="FormatDateMMDDYYYY">
	    <xsl:param name="DateTime" />
	    <!-- new date format 2010-10-13 00:00:00.0 EDT -->
	    <xsl:variable name="year">
	      <xsl:value-of select="substring($DateTime,1,4)" />
	    </xsl:variable>
	    <xsl:variable name="mo">
	      <xsl:value-of select="substring($DateTime,6,2)" />
	    </xsl:variable>
	    <xsl:variable name="day">
	      <xsl:value-of select="substring($DateTime,9,2)" />
	    </xsl:variable>
	    <xsl:variable name="hh">
	      <xsl:value-of select="substring($DateTime,12,2)" />
	    </xsl:variable>
	    <xsl:variable name="mm">
	      <xsl:value-of select="substring($DateTime,15,2)" />
	    </xsl:variable>
	    <xsl:variable name="ss">
	      <xsl:value-of select="substring($DateTime,18,2)" />
	    </xsl:variable>
	    <xsl:value-of select="$mo"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$day"/>
	    <xsl:text>/</xsl:text>
	    <xsl:value-of select="$year"/>
	</xsl:template>
</xsl:stylesheet>
